version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - /
      - /.github/actions/*
    schedule:
      interval: cron
      cronjob: "0 21 * * *"
      timezone: Australia/Brisbane
    groups:
      github-actions:
        group-by: dependency-name
